FROM env_stage_1:latest

# Define build arguments
ARG BUILD_ENV_USER_USERNAME
ARG BUILD_ENV_USER_UID
ARG BUILD_ENV_USER_GID 
ARG BUILD_ENV_USER_GROUPNAME
ARG BUILD_ENV_REPO_URL
ARG BUILD_ENV_RUNNER_TOKEN

# Set environment variables based on arguments
ENV ENV_USER_USERNAME=$BUILD_ENV_USER_USERNAME
ENV ENV_USER_UID=$BUILD_ENV_USER_UID
ENV ENV_USER_GID=$BUILD_ENV_USER_GID 
ENV ENV_USER_GROUPNAME=$BUILD_ENV_USER_GROUPNAME

ENV ENV_REPO_URL=$BUILD_ENV_REPO_URL
ENV ENV_RUNNER_TOKEN=$BUILD_ENV_RUNNER_TOKEN

# Switch to the runner user
USER runner

# Set the entrypoint to the script
ENTRYPOINT ["/home/runner/entry_point.sh"]

# Default command to run when container starts
CMD ["/home/runner/run.sh"]
