FROM debian:latest

# Define build arguments
ARG BUILD_ENV_USER_USERNAME
ARG BUILD_ENV_USER_UID
ARG BUILD_ENV_USER_GID 
ARG BUILD_ENV_USER_GROUPNAME
ARG BUILD_ENV_REPO_URL
ARG BUILD_ENV_RUNNER_TOKEN

# Set environment variables based on arguments
ENV ENV_USER_USERNAME=$BUILD_ENV_USER_USERNAME
ENV ENV_USER_UID=$BUILD_ENV_USER_UID
ENV ENV_USER_GID=$BUILD_ENV_USER_GID 
ENV ENV_USER_GROUPNAME=$BUILD_ENV_USER_GROUPNAME

ENV ENV_REPO_URL=$BUILD_ENV_REPO_URL
ENV ENV_RUNNER_TOKEN=$BUILD_ENV_RUNNER_TOKEN

RUN apt-get update && apt-get install -y --no-install-recommends dumb-init jq

# Install necessary dependencies
RUN apt-get install -y \
    bash \
    curl \
    tar \
    git \
    sudo \
    unzip \
    passwd \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /actions-runner

RUN curl -o actions-runner-linux-x64-2.319.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.319.1/actions-runner-linux-x64-2.319.1.tar.gz

RUN tar xzf actions-runner-linux-x64-2.319.1.tar.gz

RUN rm actions-runner-linux-x64-2.319.1.tar.gz

RUN ./bin/installdependencies.sh

RUN mkdir /_work

RUN chown -R runner /_work /actions-runner

COPY entry_point.sh /
RUN chmod +x /entry_point.sh

ENTRYPOINT ["/entry_point.sh"]
CMD ["./run.py"]
