# Use Ubuntu as the base image
FROM ubuntu:latest

# Define build arguments
ARG BUILD_ENV_USER_USERNAME
ARG BUILD_ENV_USER_UID
ARG BUILD_ENV_USER_GID 
ARG BUILD_ENV_USER_GROUPNAME

# Set environment variables based on arguments
ENV ENV_USER_USERNAME=$BUILD_ENV_USER_USERNAME
ENV ENV_USER_UID=$BUILD_ENV_USER_UID
ENV ENV_USER_GID=$BUILD_ENV_USER_GID 
ENV ENV_USER_GROUPNAME=$BUILD_ENV_USER_GROUPNAME

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    bash \
    curl \
    tar \
    git \
    sudo \
    unzip \
    passwd \
    && rm -rf /var/lib/apt/lists/*

# Upgrade packages
RUN apt-get upgrade -y

# Set the working directory
WORKDIR /actions-runner

# Download the latest runner package
RUN curl -o actions-runner-linux-x64-2.319.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.319.1/actions-runner-linux-x64-2.319.1.tar.gz

# Optional: Validate the hash
RUN echo "3f6efb7488a183e291fc2c62876e14c9ee732864173734facc85a1bfb1744464  actions-runner-linux-x64-2.319.1.tar.gz" | shasum -a 256 -c

# Extract the installer
RUN tar xzf ./actions-runner-linux-x64-2.319.1.tar.gz

# Create group and user using environment variables
RUN groupadd --gid ${ENV_USER_GID} ${ENV_USER_GROUPNAME} && \
    useradd --uid ${ENV_USER_UID} --gid ${ENV_USER_GID} -m ${ENV_USER_USERNAME}

# Copy entrypoint script
COPY entry_point.sh /actions-runner/entry_point.sh

# Make the entrypoint script executable
RUN chmod +x /actions-runner/entry_point.sh

# Set permissions for the working directory
RUN chown -R ${ENV_USER_UID}:${ENV_USER_GID} /actions-runner

# Switch to the new user
USER ${ENV_USER_UID}:${ENV_USER_GID}

# Set environment variables for the runner
ENV RUNNER_NAME="podman-runner"
ENV RUNNER_WORKDIR="_work"

# Set the entrypoint to the script
ENTRYPOINT ["/actions-runner/entry_point.sh"]
