# Use an official Ubuntu as the base image
FROM ubuntu:22.04

# Install required dependencies
RUN apt-get update && apt-get install -y \
    curl \
    tar \
    sudo \
    git \
    unzip \
    bash \
    libssl-dev \
    libcurl4 \
    libicu-dev \
    libkrb5-dev \
    && rm -rf /var/lib/apt/lists/*

# Add a non-root user to run the GitHub Actions runner
RUN useradd -m -d /home/runner runner

RUN ls -al /home/runner

WORKDIR /home/runner

# Download and install the GitHub Actions runner
RUN curl -o actions-runner-linux-x64-2.319.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.319.1/actions-runner-linux-x64-2.319.1.tar.gz \
    && tar xzf actions-runner-linux-x64-2.319.1.tar.gz \
    && rm actions-runner-linux-x64-2.319.1.tar.gz

# Copy entrypoint script (optional, if you have one)

COPY entry_point.sh /home/runner/entry_point.sh

RUN ls -al /home/runner/*.*

RUN chmod +x /home/runner/entry_point.sh

# Switch to the runner user
# USER runner

# Set the working directory
# WORKDIR /home/runner

# Set the entrypoint to the script
ENTRYPOINT ["/home/runner/entry_point.sh"]

# Default command to run when container starts
CMD ["/home/runner/run.sh"]
